name: "Linter"
on: [push, pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: Run style checks
        uses: coleaeason/actions-uncrustify@v1
        with:
          configPath: '.config/uncrustify.config'
