name: "Linter"
on: [push, pull_request]
jobs:
  build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@master"
      - name: "Build"
        uses: docker://josejulio/hypha-builder:release_1.7.x
        with:
          entrypoint: "bash ./uncrustify.sh -u && git diff"
        env:
            CODE: "/github/workspace/"
